#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

# exit on first non-true return value
set -o errexit
# exit if a command in a pipeline fails
set -o pipefail

git config --global user.email "noah@batteredoats.com"

git checkout -b deploy
git add --all --force ./dist/
git commit --message "Deploying $CIRCLE_SHA1"
git push origin `git subtree split --prefix dist deploy`:gh-pages --force
